// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GeneralOrder struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	UserID    pgtype.UUID      `db:"user_id" json:"user_id"`
	OrderDate pgtype.Timestamp `db:"order_date" json:"order_date"`
	// в копейках
	TotalAmount int32 `db:"total_amount" json:"total_amount"`
}

type GeneralOrderProduct struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	OrderID   pgtype.UUID `db:"order_id" json:"order_id"`
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
	// в копейках
	Price int32 `db:"price" json:"price"`
}

type GeneralProduct struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
	// в копейках
	Price int32 `db:"price" json:"price"`
}

type GeneralUser struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Name         *string     `db:"name" json:"name"`
	Email        string      `db:"email" json:"email"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	PasswordSalt string      `db:"password_salt" json:"password_salt"`
}
