services:
  pg-storage:
        image: postgres:16-alpine
        container_name: ${APP_DB_HOST}
        environment:
            POSTGRES_DB: ${APP_DB_DATABASE}
            POSTGRES_USER: ${APP_DB_USER}
            POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
            PGDATA: "/var/lib/postgresql/data/pgdata"
        ports:
            - ${APP_DB_PORT}:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-d", "${APP_DB_DATABASE}"]
            interval: 5s
            timeout: 10s
            retries: 10
            start_period: 5s 
            
  server:
    container_name: hw16_app
    build:
      context: ./../
      target: server
      dockerfile: ./hw16_docker/Dockerfile
    ports:
      - "80:${APP_HTTP_PORT}"
    tty: true
    env_file: .env
    depends_on:
      pg-storage:
        condition: service_healthy
